stages:
  train:
    cmd: python src/main.py
    deps:
    - src
    - ds
    - params.yaml

params:
- params.yaml
plots:
- dvclive/plots/metrics:
    x: step
artifacts:
  model:
    path: model.keras
    type: model
    desc: model
